# -*- coding: utf-8 -*-
"""tabpfn_logistic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6djJU6vkxFoEXnu9v3wPKh93LqMqB8u
"""

## Base library Installation
# Install Baselines for model comparison
!uv pip install catboost xgboost

# Install the datasets library for loading example data
!uv pip install datasets

# Install rich for better and more readable printing
!uv pip install rich


## TabPFN Installation optimized for Google Colab
# Install the TabPFN Client library
!uv pip install tabpfn-client

# Install tabpfn from source
# Clone the repository: shallow for speedup
!git clone --depth 1 https://github.com/PriorLabs/tabpfn

# Speeding up installation in this notebook:
# Remove torch dependency as it is already installed on colab (do not run this in your local setup)
!sed -i "/torch/d" tabpfn/pyproject.toml

# Step 3: Install using the correct directory name 'tabpfn'
!uv pip install -e "tabpfn"

# Install TabPFN extensions for additional functionalities
!git clone https://github.com/PriorLabs/tabpfn-extensions

# Speeding up installation in this notebook:
# Remove torch dependency as it is already installed on colab (do not run this in your local setup)
!sed -i "/torch/d" tabpfn-extensions/pyproject.toml

!uv pip install -e tabpfn-extensions[all]

pip install --upgrade tabpfn

import tabpfn
print("TabPFN imported successfully!")

# Standard Library Imports

# TabPFN and Extensions

try:
    from tabpfn import TabPFNClassifier, TabPFNRegressor
    from tabpfn_extensions.post_hoc_ensembles.sklearn_interface import (
        AutoTabPFNClassifier,
    )
except ImportError:
    raise ImportError(
        "Warning: Could not import TabPFN / TabPFN extensions. Please run installation above and restart the session afterwards (Runtime > Restart Session)."
    )

# Data Science & Visualization
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch

# Other ML Models
from catboost import CatBoostClassifier, CatBoostRegressor

# Notebook UI/Display
from IPython.display import Markdown, display
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt
from rich.rule import Rule
from sklearn.compose import make_column_selector, make_column_transformer

# Scikit-Learn: Data & Preprocessing
from sklearn.datasets import fetch_openml, load_breast_cancer

# Scikit-Learn: Models
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import mean_squared_error, roc_auc_score
from sklearn.model_selection import (
    KFold,
    StratifiedKFold,
    cross_val_score,
    train_test_split,
)
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from xgboost import XGBClassifier, XGBRegressor

# This transformer will be used to handle categorical features for the baseline models
column_transformer = make_column_transformer(
    (
        OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1),
        make_column_selector(dtype_include=["object", "category"]),
    ),
    remainder="passthrough",
)

from sklearn.utils import shuffle
from pathlib import Path

from sklearn.metrics import accuracy_score
import json

def split_data(X, Y, p = 0.8, seed = 123456):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = p, random_state = seed)
    return X_train, X_test, Y_train, Y_test

def performance_eval(Y_pred, Y_test):
    Y_pred = np.array(Y_pred)
    Y_test = np.array(Y_test)
    MAE = np.mean(np.abs(Y_pred - Y_test))
    RMSE = np.sqrt(np.mean((Y_pred - Y_test)**2))
    acc = accuracy_score(Y_test, Y_pred)

    #accuracy = np.mean(Y_pred == Y_test) * 100

    return MAE, RMSE, acc

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from huggingface_hub import login
login()

"""## Base

ICL4000
"""

# Set up the data directory path
DATA_DIR = Path("/content/drive/My Drive/tabPFN_update_data_March/logistic")

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)

    rows.append({"csv": str(csv_path), "mae": MAE, "rmse": RMSE, "accuracy": acc, "predictions": json.dumps([int(p) for p in y_pred])})

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR / "results_base_2.csv", index=False)
df[["mae", "rmse", "accuracy"]].describe().to_csv(DATA_DIR / "summary_statistics_base_2.csv")

df

"""ICL10"""

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:10,:]
    Y_train = Y_train[:10]

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)

    rows.append({"csv": str(csv_path), "mae": MAE, "rmse": RMSE, "accuracy": acc, "predictions": json.dumps([int(p) for p in y_pred])})

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR / "results_base_fewshot10_2.csv", index=False)
df[["mae", "rmse", "accuracy"]].describe().to_csv(DATA_DIR / "summary_statistics_base_fewshot10_2.csv")

df

"""ICL20"""

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:20,:]
    Y_train = Y_train[:20]

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)

    rows.append({"csv": str(csv_path), "mae": MAE, "rmse": RMSE, "accuracy": acc, "predictions": json.dumps([int(p) for p in y_pred])})

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR / "results_base_fewshot20_2.csv", index=False)
df[["mae", "rmse", "accuracy"]].describe().to_csv(DATA_DIR / "summary_statistics_base_fewshot20_2.csv")

"""ICL500"""

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:500,:]
    Y_train = Y_train[:500]

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)

    rows.append({"csv": str(csv_path), "mae": MAE, "rmse": RMSE, "accuracy": acc, "predictions": json.dumps([int(p) for p in y_pred])})

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR / "results_base_fewshot500_2.csv", index=False)
df[["mae", "rmse", "accuracy"]].describe().to_csv(DATA_DIR / "summary_statistics_base_fewshot500_2.csv")

"""## Row Order

ICL4000
"""

import re

def parse_predictions(s):
    # extract all numbers from the string
    nums = re.findall(r'[-+]?\d+\.?\d*', s)
    return np.array([int(float(x)) for x in nums])

base_df = pd.read_csv(DATA_DIR / "results_base_2.csv")
base_preds_dict = {
    row["csv"]: parse_predictions(row["predictions"])
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[::-1]
    Y_train = Y_train.iloc[::-1]

    model_row = TabPFNClassifier(random_state=123456)
    model_row.fit(X_train, Y_train)
    y_pred = model_row.predict(X_test)

    base_pred = base_preds_dict[str(csv_path)]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR / "results_rowOrder_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR / "summary_statistics_rowOrder_2.csv")

df

"""ICL10"""

base_df = pd.read_csv(DATA_DIR / "results_base_fewshot10_2.csv")
base_preds_dict = {
    row["csv"]: parse_predictions(row["predictions"])
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:10,:]
    Y_train = Y_train[:10]
    X_train = X_train.iloc[::-1]
    Y_train = Y_train.iloc[::-1]

    model_row = TabPFNClassifier(random_state=123456)
    model_row.fit(X_train, Y_train)
    y_pred = model_row.predict(X_test)

    base_pred = base_preds_dict[str(csv_path)]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })



df = pd.DataFrame(rows)
df.to_csv(DATA_DIR / "results_rowOrder_fewshot10_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR / "summary_statistics_rowOrder_fewshot10_2.csv")

"""ICL20"""

base_df = pd.read_csv(DATA_DIR / "results_base_fewshot20_2.csv")
base_preds_dict = {
    row["csv"]: parse_predictions(row["predictions"])
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:20,:]
    Y_train = Y_train[:20]
    X_train = X_train.iloc[::-1]
    Y_train = Y_train.iloc[::-1]

    model_row = TabPFNClassifier(random_state=123456)
    model_row.fit(X_train, Y_train)
    y_pred = model_row.predict(X_test)

    base_pred = base_preds_dict[str(csv_path)]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR / "results_rowOrder_fewshot20_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR / "summary_statistics_rowOrder_fewshot20_2.csv")

"""ICL500"""

base_df = pd.read_csv(DATA_DIR / "results_base_fewshot500_2.csv")
base_preds_dict = {
    row["csv"]: parse_predictions(row["predictions"])
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:500,:]
    Y_train = Y_train[:500]
    X_train = X_train.iloc[::-1]
    Y_train = Y_train.iloc[::-1]

    model_row = TabPFNClassifier(random_state=123456)
    model_row.fit(X_train, Y_train)
    y_pred = model_row.predict(X_test)

    base_pred = base_preds_dict[str(csv_path)]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR / "results_rowOrder_fewshot500_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR / "summary_statistics_rowOrder_fewshot500_2.csv")

"""## Num_Digits

ICL4000
"""

DATA_DIR1 = Path("/content/drive/My Drive/tabPFN_update_data_March/logistic_10_digits")

base_df = pd.read_csv(DATA_DIR / "results_base_2.csv")
base_preds_dict = {
    row["csv"]: parse_predictions(row["predictions"])
    for _, row in base_df.iterrows()
}

base_preds_dict = {
    Path(row["csv"]).name: np.array(json.loads(row["predictions"]))
    for _, row in base_df.iterrows()
}

print(list(base_preds_dict.keys())[:3])
# should now show: ['dataset_0000.csv', 'dataset_0001.csv', ...]

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR1.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    base_pred = base_preds_dict[csv_path.name]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR1 / "results_10_digits_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR1 / "summary_statistics_10_digits_2.csv")

"""ICL10"""

base_df = pd.read_csv(DATA_DIR / "results_base_fewshot10_2.csv")
base_preds_dict = {
    Path(row["csv"]).name: np.array(json.loads(row["predictions"]))
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR1.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:10,:]
    Y_train = Y_train[:10]

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    base_pred = base_preds_dict[csv_path.name]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR1 / "results_10_digits_fewshot10_2.csv", index=False)
df[["mae", "rmse", "accuracy","flip_rate"]].describe().to_csv(DATA_DIR1 / "summary_statistics_10_digits_fewshot10_2.csv")

"""ICL20"""

base_df = pd.read_csv(DATA_DIR / "results_base_fewshot20_2.csv")
base_preds_dict = {
    Path(row["csv"]).name: np.array(json.loads(row["predictions"]))
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR1.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:20,:]
    Y_train = Y_train[:20]

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    base_pred = base_preds_dict[csv_path.name]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR1 / "results_10_digits_fewshot20_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR1 / "summary_statistics_10_digits_fewshot20_2.csv")

"""ICL500"""

base_df = pd.read_csv(DATA_DIR / "results_base_fewshot500_2.csv")
base_preds_dict = {
    Path(row["csv"]).name: np.array(json.loads(row["predictions"]))
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR1.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:500,:]
    Y_train = Y_train[:500]

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    base_pred = base_preds_dict[csv_path.name]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR1 / "results_10_digits_fewshot500_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR1 / "summary_statistics_10_digits_fewshot500_2.csv")

"""## Column_Order

ICL4000
"""

DATA_DIR2 = Path("/content/drive/My Drive/tabPFN_update_data_March/logistic_shuffle")

base_df = pd.read_csv(DATA_DIR / "results_base_2.csv")
base_preds_dict = {
    Path(row["csv"]).name: np.array(json.loads(row["predictions"]))
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR2.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    base_pred = base_preds_dict[csv_path.name]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })
df = pd.DataFrame(rows)
df.to_csv(DATA_DIR2 / "results_shuffle_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR2 / "summary_statistics_shuffle_2.csv")

"""ICL10"""

base_df = pd.read_csv(DATA_DIR / "results_base_fewshot10_2.csv")
base_preds_dict = {
    Path(row["csv"]).name: np.array(json.loads(row["predictions"]))
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR2.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:10,:]
    Y_train = Y_train[:10]

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    base_pred = base_preds_dict[csv_path.name]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR2 / "results_shuffle_fewshot10_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR2 / "summary_statistics_shuffle_fewshot10_2.csv")

"""ICL20"""

base_df = pd.read_csv(DATA_DIR / "results_base_fewshot20_2.csv")
base_preds_dict = {
    Path(row["csv"]).name: np.array(json.loads(row["predictions"]))
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR2.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:20,:]
    Y_train = Y_train[:20]

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    base_pred = base_preds_dict[csv_path.name]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR2 / "results_shuffle_fewshot20_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR2 / "summary_statistics_shuffle_fewshot20_2.csv")

"""ICL500"""

base_df = pd.read_csv(DATA_DIR / "results_base_fewshot500_2.csv")
base_preds_dict = {
    Path(row["csv"]).name: np.array(json.loads(row["predictions"]))
    for _, row in base_df.iterrows()
}

from pathlib import Path
#DATA_DIR = Path("Tabpfn_data/linear_exp_all_positive2")


rows = []
files = sorted(DATA_DIR2.glob("dataset_*.csv"))[:100]
for csv_path in files:
#for csv_path in sorted(DATA_DIR.glob("dataset_*.csv")):
    df = pd.read_csv(csv_path)
    X = df.drop(columns=["Y"])
    Y = df["Y"]
    X_train, X_test, Y_train, Y_test = split_data(X, Y)
    X_train = X_train.iloc[:500,:]
    Y_train = Y_train[:500]

    model = TabPFNClassifier(random_state=123456)
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    base_pred = base_preds_dict[csv_path.name]
    flip_rate = np.mean(base_pred != y_pred)

    MAE, RMSE, acc = performance_eval(y_pred, Y_test)
    rows.append({
        "csv": str(csv_path),
        "mae": MAE,
        "rmse": RMSE,
        "accuracy": acc,
        "flip_rate": flip_rate,
        "predictions": json.dumps([int(p) for p in y_pred])
    })

df = pd.DataFrame(rows)
df.to_csv(DATA_DIR2 / "results_shuffle_fewshot500_2.csv", index=False)
df[["mae", "rmse", "accuracy", "flip_rate"]].describe().to_csv(DATA_DIR2 / "summary_statistics_shuffle_fewshot500_2.csv")
